media: public/gallery

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    filename: '{fields.title|slug}.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Date
        type: date
        options:
          format: 'dd mm yyyy'
      - name: heroImage
        label: Cover Photo
        type: image
      - name: body
        label: Content
        type: rich-text
    label: Greenland 2026 Page
    type: file
    path: src/content/pages/greenland-2026.md
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Content
        type: rich-text
